export enum LOCALE_DEFAULTS {
  token_name_short = 'SENT',
  token_name_long = 'Session Token',
  token_name_long_plural = 'Session Tokens',
  ethereum = 'Ethereum',
  network_name = 'Session Network',
  app_name = 'Session',
  arbitrum = 'Arbitrum',
  arbiscan = 'Arbiscan',
  session_download_url = 'https://getsession.org/download',
  token_name_full = 'Session Token (SENT)',
  token_bonus_title = 'Token Bonus:',
  claim_your_tokens = 'Claim Your Tokens',
  price_data_powered_by = 'Price data powered by CoinGecko',
}
